# Site settings
title:       Nguyen Van Viet
email:       vietnv@fsoft.com.vn
tagline:     'Data Science, Apache Pig, Hadoop, Blogging, Tweets, Astrophysics'
author:      VietNguyen
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://eventsteve.github.io"


# Permalinks
permalink:        none


# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: eventsteve
stackoverflow_id: kurt2305
twitter_username: kurt2305
google_plus_id:   eventsteve
linkedin_username: vietnguyen
bitcoin_url:
paypal_url:
flattr_button: 

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#markdown:     redcarpet
highlighter: rouge


#pygments:         true

permalink:    pretty

paginate:     10

sass:
  compressed: true
